Homework 1
js-tasks-ru/jsbasic-20210225_peoplecanfly-1 pull request #2
Opened 2021-02-28 12:25 UTC by Peoplecanfly1

5 Задач были решены,  все тесты пройдены.

2021-02-28 12:25 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-03-01 11:17 UTC, SinimaWath requested changes

2021-03-01 11:17 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  }
Тут есть проблема лишней вложенности -> проблема когнитивного понимания кода.
Лучшее решение: пытаться избавиться от else:
```
if (n <= 1) {
  return 1;
}

...
while (n > 1) {
  ...
}
```

Такой код проще понимать

2021-03-01 11:17 UTC, SinimaWath commented on 1-module/1-task/index.js
> +    let result = n;
Название переменной не говорящее, другой разработчик не поймет, зачем она нужна:
переменная должна говорить:
- Что она хранит
- Для чего хранит

Можно назвать: `resultedFactorial`

2021-03-01 11:17 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  return name != null && name.length >= 4 && (name.indexOf(' ')==-1) || false;
Попробуй поискать более подходящий метод для поиска, нежели чем `indexOf`

2021-03-01 11:17 UTC, SinimaWath commented on 1-module/3-task/index.js
> +  }
Лишняя вложенность, можно убрать else

2021-03-01 11:17 UTC, SinimaWath commented on 1-module/3-task/index.js
> +  if (str[0] != undefined){
А если вместо str - будет null? Что в таком случае?
Тут больше подойдет проверка:
```
if (str) {
....
}
```

2021-03-01 11:17 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  let spam1 = '1xbet';
1. Излишние переменные
2. Название переменных малоочем говорит

2021-03-01 11:17 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  str = str.toLowerCase();
Изменять аргумент - антипаттерн. 

Нужно всегда создавать новую переменную

2021-03-01 11:17 UTC, SinimaWath commented on 1-module/5-task/index.js
> +    return str.slice(0,maxlength-1) + "\u{2026}";
Можно упростить до `...`

2021-03-01 11:17 UTC, SinimaWath commented on 1-module/5-task/index.js
> +  }
Лишний else

2021-03-02 07:58 UTC, SinimaWath approved these changes

2021-03-02 07:58 UTC, merged