Homework 3
js-tasks-ru/jsbasic-20210225_peoplecanfly-1 pull request #4
Opened 2021-03-06 10:18 UTC by Peoplecanfly1

Сам недоволен решением 3ей и 4ой задачи.  :( Буду ждать ваших замечаний.

2021-03-06 10:18 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-03-07 13:20 UTC, SinimaWath requested changes

2021-03-07 13:20 UTC, SinimaWath commented on 3-module/1-task/index.js
> +    return user_array
Давай переделаем на:
1 - Array.map
2 - используй там деструкторизацию

2021-03-07 13:20 UTC, SinimaWath commented on 3-module/3-task/index.js
> +   return itemsArray.join('');
Давай переделаем на вот такую цепочку:
```
return separatedString
  .split('-')
  .map(...<тут твой код по преобразованиб>)
  .join('')
```

2021-03-07 13:20 UTC, SinimaWath commented on 3-module/3-task/index.js
> +camelize(str);
Лишнее надо убрать

2021-03-07 13:20 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  return user_result
Переделай на filter, map, join

2021-03-07 13:20 UTC, SinimaWath commented on 3-module/5-task/index.js
> +  return maxMinObj;
Это можно упростить:

return { min: Math.min(...tempArray), max: Math.max(...tempArray) }

2021-03-07 13:20 UTC, SinimaWath commented on 3-module/5-task/index.js
> +  tempArray = tempArray.map(function(item){
tempArray - непонятное имя переменной

2021-03-07 13:20 UTC, SinimaWath commented on 3-module/5-task/index.js
> +  tempArray = tempArray.map(function(item){
Вместо map, тебе нужен filter

2021-03-07 13:20 UTC, SinimaWath commented on 3-module/5-task/index.js
> +    } return null;
Так не принято писать.
не забывай перенос строки
```
if () {
  ...
  return
}

return
```

2021-03-07 13:20 UTC, SinimaWath commented on 3-module/5-task/index.js
> +  tempArray = tempArray.split(' ');
Это все можно сделать через `.`: `a.split(',').join(' ').split(' ')`

2021-03-07 13:20 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  let user_result = ''
Придерживайся одного стиля.

В названиях переменных. Если выбрал user_result, не пиши в других задача userResult. Я предлагаю выбрать camelCase(userResult). Он больше распростронен

Сейчас кажется, что каждую задачу пишет разный человек.

2021-03-08 20:09 UTC, Peoplecanfly1 commented on 3-module/1-task/index.js
> +    return user_array
Не понял только как там деструктуризацию приклеить, я просто map. прошелся и все...

2021-03-09 09:19 UTC, SinimaWath requested changes

2021-03-09 09:19 UTC, SinimaWath commented on 3-module/1-task/index.js
> +  return users.map(value => value.name)
Разбирали пример. Но без стрелочных функций: `({ name }) => name`

2021-03-09 09:19 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  .map((user,index,array) => index != array.length-1? `${user.name}, ${user.balance}\n`: `${user.name}, ${user.balance}`).join('')
Попробуй через `join('\n')`.

Не надо в map добавлять перенос

2021-03-09 09:19 UTC, SinimaWath commented on 3-module/5-task/index.js
> +  return  { min: Math.min(...inpitArray), max: Math.max(...inpitArray) }
Тут явно не хватает пустой строки.
между выражением и return

2021-03-09 09:19 UTC, SinimaWath commented on 3-module/5-task/index.js
> +  inpitArray = inputArray.split(',').join(' ').split(' ')
Незабывай , что нужно переменные создавать.

2021-03-09 09:19 UTC, SinimaWath commented on 3-module/5-task/index.js
> +    .filter(word => isFinite(word) && word != ''? word: null );
Это можно упростить и сделать без тернарного оператора.

Почитай поподробней про filter: 

Функция которую ты туда передаешь, должно возвращать true/false.

Поэтому: `word !== '' && isFinite(word)`

2021-03-09 09:20 UTC, SinimaWath requested changes

2021-03-09 09:20 UTC, SinimaWath commented on 3-module/5-task/index.js
> +  inpitArray = inputArray.split(',').join(' ').split(' ')
inpitArray - явно не лучшее название переменной.

Что делает код? Убирает неправильные значения, не числа: поэтому это - `numbersOnly`

2021-03-09 20:22 UTC, SinimaWath approved these changes

2021-03-09 20:22 UTC, merged