Homework4
js-tasks-ru/jsbasic-20210225_peoplecanfly-1 pull request #5
Opened 2021-03-12 09:09 UTC by Peoplecanfly1

Привет, с 3 задачей засада... 
1. Ужасный код, но пол дня ломал голову как оптимизировать его глобально, но ничего не сообразил ( можно минорные корректировки но глобально ничего не меняется) как из этой каши с if else что-то сделать вразумительное. 
2. Тесты не проходят, хотя изначально все проходили потом перед самим пушем решил еще раз прогнать, но все поломалось. Визуально все работает, стили применяет все ок. Что не так не могу понять. ( даже копировал примеры верстки из тестов и вставлял в верстку Index.html все работает, но тесты нет) 

Спасибо!

2021-03-12 09:09 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-03-13 13:01 UTC, SinimaWath requested changes

2021-03-13 13:01 UTC, SinimaWath commented on 4-module/1-task/index.js
> +  let ulUserList = document.createElement('ul');
Это const

2021-03-13 13:01 UTC, SinimaWath commented on 4-module/1-task/index.js
> +    liElement.innerText = user.firstName + ' ' + user.lastName;
Давай используем шаблонный строки

2021-03-13 13:01 UTC, SinimaWath commented on 4-module/1-task/index.js
> +    let liElement = document.createElement('li');
const

2021-03-13 13:01 UTC, SinimaWath commented on 4-module/3-task/index.js
> +let ApplyStylesForRow = (row) => {
- Почему с большой буквы?
- это const

2021-03-13 13:01 UTC, SinimaWath commented on 4-module/3-task/index.js
> +    return  row.cells[3].parentElement.hidden = true;
Тут return явно лишний

2021-03-13 13:01 UTC, SinimaWath commented on 4-module/3-task/index.js
> +    row.cells[1].parentElement.style.textDecoration = 'line-through'
row.cells[1].parentElement
row.cells[2].parentElement
row.cells[3].parentElement

Это все тоже самое, что и `row`. Вместо такого странно пути, просто используй елемент row и изменяй его напрямую, а не через parentElement

2021-03-13 13:01 UTC, SinimaWath commented on 4-module/3-task/index.js
> +    row.cells[2].parentElement.className = 'male'
у тебя тут баг, и вместо того, чтобы добавить класс ты его удаляешь и записываешь новый.

вместо свойства `className`, используей нормальный и понятный `classList`

2021-03-13 13:01 UTC, SinimaWath commented on 4-module/3-task/index.js
> + .forEach(ApplyStylesForRow)
Вместо splice, лучше тут прямо в forEach отсекать:
```
forEach((row, index) => {
  if (index === 0) {
    return;
  }

  applyStylesForRow();
})
```

splice(1) - операция сильно дороже, нежели чем отсечь первый елемент в forEach

2021-03-13 13:01 UTC, SinimaWath commented on 4-module/3-task/index.js
> +let ApplyStylesForRow = (row) => {
Для более простого понимания когда, целособразно разделить, эту функцию на несколько маленьких:
```
  addLineThroughIfNeeded(row);
  addAgeClassIfNeeded(row);
  addAvailableStatusClassIfNeeded(row);
```

2021-03-14 17:36 UTC, SinimaWath requested changes

2021-03-14 17:36 UTC, SinimaWath commented on 4-module/3-task/index.js
> +  }
Сейчас в такой реализации, на каждый вызов функции `applyStylesForRow `, у тебя создаются новые функции, что не хорошо

Правильно, их создать один раз:
```
const applyStylesForRow = () => {}

const addAgeClassIfNeeded = (row) => {}
const addLineThroughIfNeeded = (row) => {}
```

2021-03-15 10:53 UTC, SinimaWath approved these changes

2021-03-15 10:53 UTC, merged