первая попытка дз5.
js-tasks-ru/jsbasic-20210225_peoplecanfly-1 pull request #6
Opened 2021-03-15 21:02 UTC by Peoplecanfly1

Задача 3, как и писал в чате не проходит тесты, хотя визуально все работает.

2021-03-15 21:02 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-03-16 19:23 UTC, SinimaWath requested changes

2021-03-16 19:23 UTC, SinimaWath commented on 5-module/2-task/index.js
> +    !text.hidden ? (text.hidden = true) : (text.hidden = false);
Тернарный оператор не для этого придуман ( 

Если нужно выполнить какую-либо логику по условию, то это `if`

Но в твоем случае, можно переписать на: `text.hidden = !text.hidden`

2021-03-16 19:23 UTC, SinimaWath commented on 5-module/2-task/index.js
> +
Это явно лишние отступы

2021-03-16 19:23 UTC, SinimaWath commented on 5-module/3-task/index.js
> +  };
Лучше эту функци разбить на 3:

```
next() -> будет двигать слайдер вправо
prev() -> будет двигать слайдер влево
update() -> будет делать transform и добавлять стили
```

Сейчас у тебя намешанно все в одной и это сложно читать.

2021-03-16 19:23 UTC, SinimaWath commented on 5-module/3-task/index.js
> +      : (rightButton.style.display = "");
Тернарный оператор, тут только усложняет, так как он предназначен для возврата значений ( Давай обычный if

2021-03-16 19:23 UTC, SinimaWath commented on 5-module/3-task/index.js
> +  rightButton.style.display = "none";
В крайнем левом положение, надо скрывать кнопку налево, а не направо

2021-03-16 19:23 UTC, SinimaWath commented on 5-module/3-task/index.js
> +      : iterationQty--;
Наооборот, если нажимает вправо, то должны двигать слайды в право: `iterationQty++`, у тебя сейчас не так

2021-03-16 19:23 UTC, SinimaWath commented on 5-module/3-task/index.js
> +    carouselInner.style.transform = `translateX(-${carouselInner.offsetWidth * iterationQty}px)`;
- надо внести в саму операцию, а не добавлять строкой:
`-carouselInner.offsetWidth * iterationQty`

2021-03-16 19:23 UTC, SinimaWath commented on 5-module/3-task/index.js
> +      : (leftButton.style.display = "");
Наоборот если достигли конечной правой точки, то скрываем правую кнопку.

2021-03-16 19:23 UTC, SinimaWath commented on 5-module/3-task/index.js
> +      : (rightButton.style.display = "");
Тут скрываем левую кнопку

2021-03-18 08:49 UTC, Peoplecanfly1 commented on 5-module/3-task/index.js
> +  };
Не понял зачем разбивать направления, если это делает одна функция. Создал функцию moveSlide()

2021-03-18 08:50 UTC, Peoplecanfly1 commented on 5-module/3-task/index.js
> +    carouselInner.style.transform = `translateX(-${carouselInner.offsetWidth * iterationQty}px)`;
Вот это я не понял...

2021-03-18 18:54 UTC, SinimaWath approved these changes

2021-03-18 18:55 UTC, merged