Переоткрыл дз 6
js-tasks-ru/jsbasic-20210225_peoplecanfly-1 pull request #8
Opened 2021-03-21 15:33 UTC by Peoplecanfly1

2021-03-21 15:33 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-03-22 16:10 UTC, SinimaWath requested changes

2021-03-22 16:10 UTC, SinimaWath commented on 6-module/1-task/index.js
> +  elem; // элемент дома который потом будет добавлен в html.body.
Всегда нужно давать значение по-умолчанию.

Если свойство, не определенно, по-умолчанию, то это должен быть null

2021-03-22 16:10 UTC, SinimaWath commented on 6-module/1-task/index.js
> +    this.#setDomElement(); // Функция  которая присваивает финальный ДОМ элемент this.elem
Обычно она называетя `render

2021-03-22 16:10 UTC, SinimaWath commented on 6-module/1-task/index.js
> +    this.elem = domStructure;
Это функцию лучше разбить на 2 части.

1 - создает из шаблона елемент
2 - сохраняет елемент в this.elem


Тут слишком сложно понимать, то как выглядит верстка.

Куда наглядней переписать создание шаблона вот примерно на такой вид:


```
userTableTemplate({ users }) {
  return `
    <table>
      ${this.headerTableTemplate()}
      <tbody>
          ${this.bodyTableTemplate({ users })}
      </tbody>
    </table
  `
}


render() {
  const tempalate = this.userTableTemplate({ users: this.users });
  ...
}
```

2021-03-22 16:10 UTC, SinimaWath commented on 6-module/1-task/index.js
> +    if (target.tagName == "BUTTON") {
Лучше отвязаться от tagName, так как это слишком сильная завязка на интерфейс и от этого будет сильно сложно отвязаться

2021-03-22 16:10 UTC, SinimaWath commented on 6-module/2-task/index.js
> +    }
Вынеси это просто в стрелочную функцию метод, и у тебя тогда сохраниться контекст. Будем на лекции проходить:

```
#onCardButtonClick = () => {}
```

2021-03-22 16:10 UTC, SinimaWath commented on 6-module/2-task/index.js
> +  }
Используй хелпер, который у тебя импортирован выше: `createElement `

```

this.elem = createElement(`<div class="card">
     <остальная верстка>
    </div>`)
```

2021-03-25 19:18 UTC, SinimaWath requested changes

2021-03-25 19:18 UTC, SinimaWath commented on 6-module/3-task/index.js
> +    return allSlidesTemplate;
Давай переделаем на map

2021-03-25 19:18 UTC, SinimaWath commented on 6-module/1-task/index.js
> +  }
Это можно переписать на map :)

2021-03-25 19:18 UTC, SinimaWath commented on 6-module/3-task/index.js
> +    }
А почему это функции в функции?

Сделай их обычными методами твоего класса

2021-03-25 19:18 UTC, SinimaWath commented on 6-module/3-task/index.js
> +    };
Это тоже отдельный метод класса

2021-03-25 19:18 UTC, SinimaWath commented on 6-module/3-task/index.js
> +    this.#moveSlide(); // Добавляем возможность двигать слайдер
moveSlide - судя из названия, обозначает - двигать слайдер. А у тебя тут инициализация

2021-03-25 19:18 UTC, SinimaWath commented on 6-module/3-task/index.js
> +    this.#moveSlide(); // Добавляем возможность двигать слайдер
Нет необходимости в отдельной функции moveSlide, когда ты ее разобьешь на методы класса

2021-03-25 19:18 UTC, SinimaWath commented on 6-module/3-task/index.js
> +    this.elem = document.createElement("div");
А зачем делать createElement("div")?

Используй хэлпер createElement в методе рендер:
```

this.elem = createElement(`
<div class="carousel">
    <div class="carousel__arrow carousel__arrow_right">
      <img src="/assets/images/icons/angle-icon.svg" alt="icon">
    </div>
    <div class="carousel__arrow carousel__arrow_left">
      <img src="/assets/images/icons/angle-left-icon.svg" alt="icon">
    </div>
    <div class="carousel__inner">
      ${this.#makeSlidesLayout({ products: this.slides })}
    </div>
</div>
`)
```

2021-03-25 19:18 UTC, SinimaWath commented on 6-module/3-task/index.js
> +    this.elem = document.createElement("div");
Тогда в таком случае не надо будет делать: `this.elem.classList.add("carousel");`

2021-03-27 12:01 UTC, SinimaWath requested changes

2021-03-27 12:01 UTC, SinimaWath commented on 6-module/3-task/index.js
> +    this.sliderData = null;
Это приватное поле

2021-03-27 12:01 UTC, SinimaWath commented on 6-module/3-task/index.js
>      this.slides = slides;
Это тоже приватное поле

2021-03-27 12:01 UTC, SinimaWath commented on 6-module/3-task/index.js
> +    let slide = { id: null };
Зачем делать такой временный обьект? 

Почему не: `const slideId =event.target.closest(".carousel__slide").dataset.id `;

2021-03-27 12:01 UTC, SinimaWath commented on 6-module/3-task/index.js
> +    ) {
Условие не очень понятное. Такое сложно, стоит обычно вынести в отдельную переменную:

`const isRightArrow = ....`

2021-03-27 12:01 UTC, SinimaWath commented on 6-module/3-task/index.js
> +        .classList.contains("carousel__arrow_right")
Можно упростить до: `target.closest('.carousel__arrow_right')`

2021-03-27 12:01 UTC, SinimaWath commented on 6-module/3-task/index.js
> +    }
Давай переделаем на делегирование тоже?

У тебя в верстке у елементов уже есть data-id

2021-03-28 14:16 UTC, SinimaWath approved these changes

2021-03-28 14:17 UTC, merged